src/dj_mlp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include('import_csv.urls', namespace='import_csv')),
    path('', RedirectView.as_view(url='upload/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/import_csv/urls.py
from django.urls import path
from .views import import_file_view, assign_movies_view
app_name = 'import_csv'

urlpatterns = [
    path('', import_file_view, name='upload-view'),
    path('assign_movies', assign_movies_view, name='assign-movies'),
]

src/products/urls.py
from django.urls import path
from .views import chart_select_view

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-products-view')
]

src/import_csv/models.py
from django.contrib.auth.models import User
from django.db import models


class Csv(models.Model):
    file_name = models.FileField(max_length=100)
    uploaded = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=False)

    def __str__(self):
        return f"File: {self.file_name}"


class Profile(models.Model):
    PROFILE_LEVEL_CHOICES = [
        ('ADVANCED', 'Advanced'),
        ('INTERMEDIATE', 'Intermediate'),
        ('BEGINNER', 'Beginner'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_level = models.CharField(max_length=100
                                     , choices=PROFILE_LEVEL_CHOICES
                                     , default='INTERMEDIATE')


class Movie(models.Model):
    movie_id = models.CharField(max_length=100)
    movie_name = models.TextField()
    movie_user = models.ForeignKey(
        User, null=True, blank=True, default=None, on_delete=models.SET_NULL
    )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Movie name: {self.movie_name}"

src/products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=220)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)


class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField(blank=True)
    salesman = models.ForeignKey(User, on_delete=models.CASCADE)
    # change required
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.price
        super().save(*args, **kwargs)

    def __str__(self):
        return "Sold {} - {} items for {}".format(self.product.name, self.quantity, self.total_price)

src/import_csv/forms.py
from django import forms
from .models import Csv, Movie
from django.contrib.auth.models import User

class CsvForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name',)


class AssignMovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ("movie_id", "movie_name", "movie_user")

src/import_csv/views.py
from django.shortcuts import render
from .forms import CsvForm, AssignMovieForm
from .models import Movie
import csv
from django.contrib.auth.models import User
from django.forms import modelformset_factory


# Create your views here.
def import_file_view(request):
    error_message = None
    success_message = None

    if request.method == "POST":
        form = CsvForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save()

            try:
                with open(obj.file_name.path, 'r') as f:
                    reader = csv.reader(f)
                    row_cnt = 0
                    for row in reader:
                        movie, _ = Movie.objects.get_or_create(movie_id=row[0], movie_name=row[1])
                        row_cnt += 1

                obj.success = True
                obj.save()

                if row_cnt > 1:
                    tag = "rows"
                else:
                    tag = "row"

                success_message = f"File uploaded successfully: {row_cnt} {tag} imported"

            except Exception as exc:
                error_message = f"File import error: {str(exc)}"

    else:
        form = CsvForm()

    context = {
        'form': form,
        'success_message': success_message,
        'error_message': error_message
    }
    return render(request, 'import/upload.html', context)


def reset_movies():
    movies = Movie.objects.all()

    for movie in movies:
        movie.movie_user = None
        movie.save()


def assign_movies_view(request):
    error_message = None
    AssignMovieFormSet = modelformset_factory(Movie, form=AssignMovieForm)
    formset = None

    if request.method == 'POST':

        if Movie.objects.count() == 0:
            error_message = f"Import movies first!"
        else:
            if "assign" in request.POST:
                formset = AssignMovieFormSet(request.POST)
                formset.clean()
                for form in formset:
                    movie_id = form.cleaned_data.get("movie_id", None)
                    movie_user = form.cleaned_data.get("movie_user", None)

                    if form.has_changed():
                        movie = Movie.objects.get(movie_id=movie_id)
                        movie.movie_user = movie_user
                        movie.save()
            else:
                reset_movies()
                formset = AssignMovieFormSet()
    else:
        formset = AssignMovieFormSet()

    context = {
        'formset': formset,
        'error_message': error_message
    }
    return render(request, 'import/assign_movies.html', context)

src/products/views.py
from django.shortcuts import render
from .models import Product, Purchase
import pandas as pd


# Create your views here.
def chart_select_view(request):
    error_message = None
    context = {}
    df = None

    try:
        product_df = pd.DataFrame(Product.objects.all().values())
        purchase_df = pd.DataFrame(Purchase.objects.all().values())
        product_df['product_id'] = product_df['id']

        if purchase_df.shape[0] > 0:
            df = pd.merge(purchase_df, product_df, on='product_id').drop(['id_y', 'date_y'], axis=1) \
                .rename({'id_x': 'id', 'date_x': 'date'}, axis=1)
            context = {
                'df': df.to_html(),
                'error_message': error_message
            }
        else:
            error_message = 'No records in the database'
            context = {
                'df': df,
                'error_message': error_message
            }
    except:
        product_df = None
        purchase_df = None
        error_message = 'No records in the database'

        # context = {
        #     'df': df,
        #     'error_message': error_message
        # }

    return render(request, 'products/main.html', context)

src/import_csv/templates/import/assign_movies.html
{% extends 'base.html' %}

{% block title %}Assign User{% endblock title %}

{% block content %}
    {% if error_message %}
        <div class="ui red message">
            <i class="close icon"></i>
            <div class="header">
                {{ error_message }}
            </div>
        </div>
    {% endif %}

    <h1>Assign Users To Movies</h1>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <table id="movie_user_table" class="display" style="width:100%">
          <thead>
            <tr>
                <th class="single line">Movie ID</th>
                <th class="single line">Movie Name</th>
                <th class="single line">Assigned User</th>
            </tr>
          </thead>
          <tbody>
            {% for form in formset %}
                {% if form.instance.movie_id %}
                    <tr>
                        {{ form.movie_id.as_hidden }}
                        {{ form.movie_name.as_hidden }}
                        <td>{{ form.instance.movie_id }}</td>
                        <td>{{ form.instance.movie_name }}</td>
                        <td>{{ form.movie_user }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
          </tbody>
        </table>
        <button name = "reset" type="submit" class="ui positive button">Reset Assignment</button>
        <button name = "assign" type="submit" class="ui positive button">Assign Users</button>
    </form>

{% endblock %}

src/import_csv/templates/import/upload.html
{% extends 'base.html' %}

{% block title %}Import{% endblock title %}

{% block content %}
    {% if success_message %}
        <div class="ui blue message">
            <i class="close icon"></i>
            <div class="header">
                {{ success_message }}
            </div>
        </div>
    {% endif %}

    {% if error_message %}
        <div class="ui red message">
            <i class="close icon"></i>
            <div class="header">
                {{ error_message }}
            </div>
        </div>
    {% endif %}

    <h1>Import Movies</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="ui form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="ui positive button">Add Data</button>
    </form>

{% endblock content %}

src/products/templates/products/main.html
{% extends 'base.html' %}

{% block title %}performance{% endblock title %}

{% block content %}

{{ df | safe}}
<hr>


<div>
    <form action="" method="POST" class="ui form ">
        {% csrf_token %}
        <div class="field">
            <label>Choose a chart type: </label>
            <div class="ui selection dropdown">
                <input type="hidden" name="sales">
                <i class="dropdown icon"></i>
                <div class="default text">----</div>
                <div class="menu">
                    <div class="item" value="bar">Bar Plot</div>
                    <div class="item" value="line">Line Plot</div>
                    <div class="item" value="count">Count Plot</div>
                </div>
            </div>
        </div>
        <div class="field">
            <div class="two fields">
                <div class="field">
                    <label>Date From: </label>
                    <input type="date" name="date_from">
                </div>
                <div class="field">
                    <label>Date To: </label>
                    <input type="date" name="date_to">
                </div>
            </div>
        </div>
        <button class='ui primary button' type='submit'>Select</button>
    </form>
</div>

{% endblock content %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>Movie Launcher - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class='ui container'>
    {% block content %}
    {% endblock content %}
    </div>

   <script type='text/javascript' src={% static 'main.js' %}></script>
  </body>
</html>

src/templates/navbar.html
{% url 'import_csv:upload-view' as path_to_upload %}
{% url 'import_csv:assign-movies' as path_to_assign_movies %}
{% url 'import_csv:assign-movies' as path_to_assign_movies %}

<div class="ui secondary pointing menu">
  <a href= {{path_to_upload}}  class="{% if request.path == path_to_upload%}active{% endif %} item">
    Import
  </a>
  <a href= {{path_to_assign_movies}} class="{% if request.path == path_to_assign_movies%}active{% endif %} item">
    Assign Users
  </a>
  <a href= "{% url 'admin:index' %}" class="item" target ="_blank">
    Site Admin
  </a>
</div>